import = ["/home/zooboo/.config/alacritty/nord.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10

[font.bold]
family = "Caskaydia Cove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Caskaydia Cove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Caskaydia Cove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Caskaydia Cove Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/bash"

[window]
opacity = 0.6

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
